import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const languages = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "ru", name: "Russian", nativeName: "Русский" },
  { code: "zh", name: "Chinese", nativeName: "中文" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
  { code: "ko", name: "Korean", nativeName: "한국어" },
  { code: "ar", name: "Arabic", nativeName: "العربية" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { code: "th", name: "Thai", nativeName: "ไทย" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "pl", name: "Polish", nativeName: "Polski" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά" },
  { code: "he", name: "Hebrew", nativeName: "עברית" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu" },
  { code: "fa", name: "Persian", nativeName: "فارسی" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili" },
  { code: "ro", name: "Romanian", nativeName: "Română" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar" },
  { code: "cs", name: "Czech", nativeName: "Čeština" },
  { code: "sv", name: "Swedish", nativeName: "Svenska" },
  { code: "da", name: "Danish", nativeName: "Dansk" },
  { code: "fi", name: "Finnish", nativeName: "Suomi" },
  { code: "no", name: "Norwegian", nativeName: "Norsk" },
  { code: "sk", name: "Slovak", nativeName: "Slovenčina" },
  { code: "hr", name: "Croatian", nativeName: "Hrvatski" },
  { code: "ca", name: "Catalan", nativeName: "Català" },
  { code: "fil", name: "Filipino", nativeName: "Filipino" },
  { code: "lv", name: "Latvian", nativeName: "Latviešu" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili" },
  { code: "ro", name: "Romanian", nativeName: "Română" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar" },
  { code: "cs", name: "Czech", nativeName: "Čeština" },
  { code: "sv", name: "Swedish", nativeName: "Svenska" },
  { code: "da", name: "Danish", nativeName: "Dansk" },
  { code: "fi", name: "Finnish", nativeName: "Suomi" },
  { code: "no", name: "Norwegian", nativeName: "Norsk" },
  { code: "sk", name: "Slovak", nativeName: "Slovenčina" },
  { code: "hr", name: "Croatian", nativeName: "Hrvatski" },
  { code: "ca", name: "Catalan", nativeName: "Català" },
  { code: "fil", name: "Filipino", nativeName: "Filipino" },
  { code: "lv", name: "Latvian", nativeName: "Latviešu" },
  { code: "et", name: "Estonian", nativeName: "Eesti" },
  { code: "sl", name: "Slovenian", nativeName: "Slovenščina" },
  { code: "is", name: "Icelandic", nativeName: "Íslenska" },
  { code: "mt", name: "Maltese", nativeName: "Malti" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "sn", name: "Shona", nativeName: "ChiShona" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "jw", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "ba", name: "Bashkir", nativeName: "Башҡорт" },
  { code: "sc", name: "Sardinian", nativeName: "Sardu" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "oc", name: "Occitan", nativeName: "Occitan" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt" },
  { code: "kl", name: "Greenlandic", nativeName: "Kalaallisut" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "to", name: "Tongan", nativeName: "Faka Tonga" },
  { code: "mi", name: "Māori", nativeName: "Māori" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", nativeName: "ဗမာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "si", name: "Sinhalese", nativeName: "සිංහල" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  
]

async function main() {
  console.log('Start seeding languages...')
  
  for (const language of languages) {
    const result = await prisma.language.upsert({
      where: { code: language.code },
      update: language,
      create: language,
    })
    console.log(`Upserted language with code: ${result.code}`)
  }
  
  console.log('Seeding finished.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  }) 